---
title: "Text Mining with R"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Description

This project includes my notes/code for working through Julia Silge and David Robinson's "Text Mining with R" (O'Reilly, 2017). I've also put together an IOSlides presentation to display plots from the book (for the purpose of practicing IOSlides).

http://tidytextmining.com

https://github.com/dgrtwo/tidy-text-mining

http://rmarkdown.rstudio.com/ioslides_presentation_format.html

## Log

20171226 - Finished Chapter 5

20171225 - Merry Christmas! Began financial article case study. Difficult loading
tm.plugin.webmining package due to Java depenencies. 

20171224 - Up to the mining financial articles example in Chapter 5

20171223 - Up to quanteda package in Chapter 5

20171222 - Finished Chapter 4

20171221 - Up to network analysis in Chapter 4

20171218 - Created IOSlides presentation with interactive plot

20171216 - Started Chapter 4 - pick back up with "Using bigrams to provide context in sentiment analysis""

20171215 - Finished Chapter 3

20171213 - Finished Chapter 2

20171212 - finished Chapter 1/starting in on Chapter 2

20171210 - through Chapter 1 - gutenbergr multi-text frequencies

## Related Resources

https://cran.r-project.org/web/views/NaturalLanguageProcessing.html

Check out these packages for natural langauge processing:

* coreNLP
* cleanNLP
* sentimentr