---
title: "Textmining Shiny IOSlides"
runtime: shiny
output: ioslides_presentation
---

```{r setup, include=FALSE}
library(dplyr)
library(janeaustenr)
library(tidytext)
library(ggplot2)

book_words <- austen_books() %>%
  unnest_tokens(word, text) %>%
  count(book, word, sort = TRUE) %>%
  ungroup()

total_words <- book_words %>% 
  group_by(book) %>% 
  summarize(total = sum(n))

book_words <- left_join(book_words, total_words)

ggplot(book_words, aes(n/total, fill = book)) +
  geom_histogram(show.legend = FALSE) +
  xlim(NA, 0.0009) +
  facet_wrap(~book, ncol = 2, scales = "free_y")

knitr::opts_chunk$set(echo = FALSE)
```

## Sample Static ggplot
```{r, echo=FALSE, message=FALSE, warning=FALSE}
ggplot(book_words, aes(n/total, fill = book)) +
  geom_histogram(show.legend = FALSE) +
  xlim(NA, 0.0009) +
  facet_wrap(~book, ncol = 2, scales = "free_y")
```

## Sample Interactive ggplot
```{r, echo=FALSE, message=FALSE, warning=FALSE}
inputPanel(
  selectInput("book.select", label = "Select Book:",
              choices = c("Pride & Prejudice",
                          "Sense & Sensibility",
                          "Emma",
                          "Mansfield Park",
                          "Northanger Abbey",
                          "Persuasion"), selected = "Pride & Prejudice")
)

renderPlot({
  book_words %>% 
    filter(book == input$book.select) %>% 
    ggplot(aes(n/total, fill = book)) +
    geom_histogram(show.legend = FALSE) +
    xlim(NA, 0.0009) 
})

```
